Transitive Comparator for script sorting
GodotModding/godot-mod-loader pull request #277
Opened 2023-06-16 07:25 UTC by boardengineer

The current algorithm returns a random result unless a is in b's type hierarchy.  Random results are disallowed in the sort_custom API

https://docs.godotengine.org/en/3.5/classes/class_array.html?highlight=sort_custom

The new algorithm sorts alphabetically by names in the type hierarchy paths until one of the trees stop then it sorts the shorter tree first.

Aims to fix the following errors that gets spammed at startup (and i think causes startup crashes):

E 0:00:00.815   SortArray<class Variant,struct _ArrayVariantSortCustom,1>::partitioner: bad comparison function; sorting will be broken
  <C++ Source>  .\core/sort_array.h:179 @ SortArray<class Variant,struct _ArrayVariantSortCustom,1>::partitioner()
  <Stack Trace> script_extension.gd:39 @ handle_script_extensions()
                mod_loader.gd:164 @ _load_mods()
                mod_loader.gd:67 @ _init()

2023-06-16 13:44 UTC, Qubus0 reviewed
Looks good. Thank you for the contribution 😃 

Comparing the stacks looks wrong at first glance since it just compares the scripts at the same index in the stack, but with `push_front` it starts to make sense. Both stacks start after the native Godot classes and work up from there. No matter where both stacks would go apart, they will always arrive at the same vanilla script at the same time. 
On that note - I assume `get_base_script` does not return Godot classes, right? Otherwise it could cause issues

Another thing: The code does not use `ModLoaderStore.loaded_vanilla_parents_cache.keys()` anymore. I think this was the only place where it was used, so it can be removed from the store and also where it is updated. Please have a look

2023-06-16 13:44 UTC, Qubus0 commented on addons/mod_loader/internal/script_extension.gd
> +		var a_stack = []
please try to use static types -> `:=`
(also applies to the rest of the method)

2023-06-16 16:39 UTC, boardengineer commented on addons/mod_loader/internal/script_extension.gd
> +		var a_stack = []
Added static types and removed cache, Thank you

2023-06-17 07:47 UTC, Qubus0 approved these changes
nice, thank you.

2023-06-17 15:40 UTC, Qubus0 requested changes
blocked until the bug we discussed on discord is fixed

2023-06-17 20:01 UTC, Qubus0 approved these changes
important fix, thank you 👍

2023-06-17 23:14 UTC, merged