Spliting Date & Time Methods in to Dedicated Class
GodotModding/godot-mod-loader pull request #346
Opened 2023-10-19 10:18 UTC by AlajeBash

# DESCRIPTION

I Created a new `GDScript` file with the name `time.gd` to hold the `ModLoaderTime` class.
And in `time.gd`, i define the `ModLoaderTime` class and move the time-related utility methods into it.

2023-10-19 10:40 UTC, KANAjetzt requested changes
Thanks for your PR 😃
Let me know if anything is unclear.

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +class_name ModLoaderTime
```suggestion
class_name ModLoaderTime
extends Node
```

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +class_name ModLoaderTime
Also please add a short comment above the `class_name` that describes this class.
See the top comment of [log.gd](https://github.com/GodotModding/godot-mod-loader/blob/main/addons/mod_loader/api/log.gd) for an example.

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/log.gd
> +    print("Date-Time: ", date_time_str)
Can you explain why this was added? 
I don't see a need for this.

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/log.gd
> +var time_utils = ModLoaderTime.new()
No need to import the `ModLoaderTime` class, classes are global and the methods are static, so you can just replace the calls to the date function with `ModLoaderTime.theDateFunction`

For example here:
https://github.com/GodotModding/godot-mod-loader/blob/19a7b7fc484a98969d9a82ff8f402a3a30f08246/addons/mod_loader/api/log.gd#L508

Change this to `ModLoaderTime.get_date_string()`

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +static func _get_time_string() -> String:
The underscore `_` is used to denote "private" methods in a class that should not be accessed by modders. In this case, we're moving the Time functions to a separate class that modders can use if they have a need for them. So, we can remove the underscores `_` from the function names.

```suggestion
static func get_time_string() -> String:
```

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +static func _get_date_string() -> String:
```suggestion
static func get_date_string() -> String:
```

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +static func _get_date_time_string() -> String:
```suggestion
static func get_date_time_string() -> String:
```

2023-10-19 10:40 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +
Please add 2 empty lines between functions.

2023-10-19 16:51 UTC, AlajeBash commented on addons/mod_loader/api/log.gd
> +var time_utils = ModLoaderTime.new()
resolved

2023-10-20 06:33 UTC, KANAjetzt requested changes

2023-10-20 06:33 UTC, KANAjetzt commented on addons/mod_loader/api/log.gd
> +	log_file.store_string('%s Created log' % ModLoaderTime.get_date_string())
Please search the entire codebase for calls to the Time utility functions and update them to `ModLoaderTime`. In Godot, you can press `Ctrl` + `Alt` + `F` to search the entire project. Additionally, please perform a test run. You can create an empty Godot project and [symlink](https://en.wikipedia.org/wiki/Symbolic_link) the repository into the addons folder for testing.

2023-10-20 06:33 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +# ModLoaderTime class
```suggestion
```

2023-10-20 06:33 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +
One empty line missing.
If you are interested yo can read up on the [GDScript style guide here](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html).

2023-10-21 12:34 UTC, AlajeBash commented on addons/mod_loader/api/log.gd
> +	log_file.store_string('%s Created log' % ModLoaderTime.get_date_string())
@KANAjetzt is there need for `Internal Date Time` functions in [addons/mod_loader/setup/setup_log.gd](addons/mod_loader/setup/setup_log.gd) ?

2023-10-21 20:35 UTC, KANAjetzt commented on addons/mod_loader/api/log.gd
> +	log_file.store_string('%s Created log' % ModLoaderTime.get_date_string())
You can keep everything related to the setup (everything in the setup directory) as it is. The setup must be completely separate, which is why there is a lot of duplicated code in these files.

2023-10-21 22:40 UTC, AlajeBash commented on addons/mod_loader/api/log.gd
> +	log_file.store_string('%s Created log' % ModLoaderTime.get_date_string())
Ok thank you

2023-10-22 09:49 UTC, KANAjetzt requested changes

2023-10-22 09:49 UTC, KANAjetzt commented on addons/mod_loader/api/time.gd
> +
The empty line is still missing.

2023-10-22 09:49 UTC, KANAjetzt commented on addons/mod_loader/api/log.gd
> +	log_file.store_string('%s Created log' % ModLoaderTime.get_date_string())
There is one more call to `_get_date_time_string()`

https://github.com/GodotModding/godot-mod-loader/blob/a73641fc27ec422e592decf5f34bddfa78627663/addons/mod_loader/api/log.gd#L479

2023-10-24 06:25 UTC, KANAjetzt commented
@AlajeBash, you requested a review but did not apply my requested changes. Additionally, there is now a second PR for this? Please check my last comments and make the requested changes. Let me know if you need any help or if something is unclear.

2025-06-11 07:22 UTC, closed without merging