feat: Add `rename_profile()` to `ModLoaderUserProfile`
GodotModding/godot-mod-loader pull request #352
Opened 2023-10-24 21:16 UTC by kyooosukedn

closes #287 

Hi, for this change I modified and reference myself to method create_profile as @KANAjetzt in https://github.com/GodotModding/godot-mod-loader/blob/development/addons/mod_loader/api/profile.gd :)

2023-10-25 08:28 UTC, KANAjetzt requested changes
Thanks for your PR! Let me know if you have any questions or if something is unclear.

2023-10-25 08:28 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +		return false
For renaming a profile, you want to check the opposite. If there is no user profile with the provided `old_profile_name`, you should log the error and return `false`.

2023-10-25 08:28 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +	return is_save_success
There is some weird indentation going on here.
Please test your Code by [running the ModLoader in Godot](https://github.com/GodotModding/godot-mod-loader/wiki/Godot-Project-Setup).

2023-10-25 08:28 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +	ModLoaderStore.user_profiles.erase(old_profile_name) = new_profile
```suggestion
	ModLoaderStore.user_profiles.erase(old_profile_name)
```

2023-10-25 08:28 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +  var profile_to_rename = ModLoaderStore.user_profiles[old_profile_name]
You want to use [`.duplicate(true)`](https://docs.godotengine.org/en/3.5/classes/class_dictionary.html#class-dictionary-method-duplicate) to create a new instance of the dictionary. Without this, only a reference is passed to `profile_to_rename`.

```suggestion
  var profile_to_rename = ModLoaderStore.user_profiles[old_profile_name].duplicate(true)
```

2023-10-25 21:04 UTC, kyooosukedn commented
@KANAjetzt Thank you very much for your review, now I think I have corrected the changes the way you suggested. Question for "running modloader in godot" do I need to take the mod developer route to test it?

2023-10-26 05:15 UTC, KANAjetzt commented
For starters, you can create an empty Godot Project and follow the steps on [this page](https://github.com/GodotModding/godot-mod-loader/wiki/Godot-Project-Setup).

If you get this working, you can look into [symlinking](https://en.wikipedia.org/wiki/Symbolic_link) the `addons` directory into this project.

That will allow you to edit the code inside Godot, where you will get some syntax errors to fix.

If no compile errors show up anymore, you can look into the *mod developer route* and add the rename functionality to the [example user profile UI mod](https://github.com/GodotModding/GodotModding-UserProfileUI).

This would be ideal, but it might be a bit overwhelming if you've never used Godot. So feel free to just edit your code inside Godot to get the syntax error messages, and I will review your code again.

2023-10-31 15:33 UTC, kyooosukedn commented
Hi @KANAjetzt sorry that it took so long, i corrected some changes as I am able to get the syntax error now

2023-11-04 23:16 UTC, KANAjetzt requested changes
Almost there - thanks for your work! 👍
As I said in the review, it's important to test things in practice. I added the rename feature to the example UI mod and found the mentioned issues.

2023-11-04 23:16 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +	var profile_to_rename = ModLoaderStore.user_profiles[old_profile_name].duplicate(true)
I renamed it from `profile_to_rename` -> `profile_renamed` - I feel like this is more clear because it is the reference to the renamed profile.

2023-11-04 23:16 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +		ModLoaderStore.current_user_profile[new_profile_name]
```suggestion
	# Set it as the current profile if it was the current profile
	if ModLoaderStore.current_user_profile.name == old_profile_name:
		set_profile(profile_renamed)
```

We can't check for `ModLoaderStore.user_profiles[old_profile_name]` because it got erased a few lines above.

2023-11-04 23:16 UTC, KANAjetzt commented on addons/mod_loader/api/profile.gd
> +	var profile_to_rename = ModLoaderStore.user_profiles[old_profile_name].duplicate(true)
I also realized that we are duplicating a Resource here, and that comes with some caveats ([here are the Docs](https://docs.godotengine.org/en/3.5/classes/class_resource.html#class-resource-method-duplicate)).

I added the `as ModUserProfile` to cast the type. Without that, it's just a generic `Resource`, and `set_profile(profile_renamed)` will not work. In addition, I had to change [mod_user_profile.gd](https://github.com/GodotModding/godot-mod-loader/blob/main/addons/mod_loader/resources/mod_user_profile.gd). As described in the docs, only exported properties are duplicated, so I added the two `export` to the file:
```gdscript
export var name := ""
export var mod_list := {}
```

2023-11-05 14:23 UTC, kyooosukedn commented
Thank you again :) I'm sorry I don't have the chance yet to really dive deep into it..

2025-01-25 13:19 UTC, KANAjetzt approved these changes
Fixed all the open issues ready to merge from my side maybe you can take quick look @Qubus0

2025-01-25 14:12 UTC, Qubus0 approved these changes
exports are added to make debugging easier i assume?

2025-01-26 20:51 UTC, KANAjetzt commented
Mostly because the props only get duplicated if they are exported.

> Duplicates this resource, returning a new resource with its exported or [@GlobalScope.PROPERTY_USAGE_STORAGE](https://docs.godotengine.org/en/3.6/classes/class_%40globalscope.html#class-globalscope-constant-property-usage-storage) properties copied from the original.
> https://docs.godotengine.org/en/3.6/classes/class_resource.html#class-resource-method-duplicate

2025-01-26 21:03 UTC, merged