feat: :sparkles: added `refresh_config_data()` and `refresh_current_c…
GodotModding/godot-mod-loader pull request #374
Opened 2024-03-21 15:24 UTC by KANAjetzt

Allows refreshing of config data at any time during runtime.

Adds 2 new functions:

**`func refresh_config_data(config: ModConfig) -> ModConfig:`**
Refreshes the data of the provided configuration by reloading it from the config file.

**`func refresh_current_configs() -> void:`**
Iterates over all mods to refresh the data of their current configurations, if available.
Compares the previous configuration data with the refreshed data and emits the `current_config_changed` signal if changes are detected.

2024-03-21 20:25 UTC, Qubus0 requested changes

2024-03-21 20:25 UTC, Qubus0 commented on addons/mod_loader/api/config.gd
> +			ModLoader.current_config_changed.emit(config)
this signal is missing from the pr. I'd also add the mod id to the signal for clean access

2024-03-22 17:48 UTC, KANAjetzt commented on addons/mod_loader/api/config.gd
> +			ModLoader.current_config_changed.emit(config)
the `current_config_changed` signal?

2024-03-22 17:58 UTC, Qubus0 commented on addons/mod_loader/api/config.gd
> +			ModLoader.current_config_changed.emit(config)
oh that's an existing one. and it also has the id. ignore this then

2024-03-22 17:59 UTC, Qubus0 approved these changes

2024-03-22 18:00 UTC, merged