feat: :construction: first draft of the export plugin
GodotModding/godot-mod-loader pull request #408
Opened 2024-08-22 07:00 UTC by KANAjetzt

The plan is to automate the creation of hooks for each function in all GDScripts.

2024-11-07 15:57 UTC, pirey0 commented on addons/mod_loader/internal/mod_hook_preprocessor.gd
> +	if ModLoaderStore.get("any_mod_hooked") and ModLoaderStore.any_mod_hooked:
I think the` ModLoaderStore.get("any_mod_hooked")` kills all the performance-benefits of checking ModLoaderStore.any_mod_hooked. 
This was originally a way to reduce the modding overhead when running a modless version of a game. 
2 topics:
 - can we somehow skip the ` ModLoaderStore.get("any_mod_hooked")`  call?
 - can we skip the check altogether when dynamically generating the scripts, since there we only create the methods when hooks actually exist.

2024-11-07 16:38 UTC, pirey0 requested changes
Only reviewed the code itself, did not run any tests. 
Only change we should really look into is the `any_mods_hooked` one, remaining feedback is just for code quality.

2024-11-07 16:38 UTC, pirey0 commented on addons/mod_loader/mod_loader.gd
> +	return false
Don't see any reference to this call, looks like some mid-development method that was never used/implemented?

2024-11-07 16:38 UTC, pirey0 commented on addons/mod_loader/_export_plugin/plugin.cfg
> +author="KANA"
Might make sense to have https://github.com/GodotModding as author instead of just KANA

2024-11-07 16:38 UTC, pirey0 commented on addons/mod_loader/api/mod.gd
> +		ModLoaderStore.hooked_script_paths[script_path] = null
Nitpick: We are using a Dictionary as a Hashset here.
Even though we do not intend to use the dictionary value, it might make sense to store a "truthy" value instead of null so that both `has `and `get` can be used in if checks. (I would just use True)
Currently `hooked_script_paths.get(script_path, false)` would always be falsey, which is not the expected interpretation

2024-11-07 16:38 UTC, pirey0 commented on addons/mod_loader/internal/mod_hook_preprocessor.gd
> +		func is_func_moddable(method: Dictionary):
why are we inlining this function? For me it just worsens readability.

2024-11-07 16:38 UTC, pirey0 commented on addons/mod_loader/internal/mod_hook_preprocessor.gd
> +	var stack := []
No need to use a stack here, could just be another accumulator, just doing +1 on "(" and -1 on ")"

2024-11-08 10:13 UTC, merged

2024-11-08 10:14 UTC, KANAjetzt commented
The requested changes will be addressed in subsequent PRs.