Better hooks
GodotModding/godot-mod-loader pull request #436
Opened 2024-11-16 03:40 UTC by Qubus0

allows modders to manipulate parameters and return values similarly to how script extensions work.
also docs

2024-11-17 19:09 UTC, KANAjetzt approved these changes
Tested with the provided example project, in editor and as exported game.

Amazing work - thanks!

2024-11-17 19:09 UTC, KANAjetzt commented on addons/mod_loader/api/hook.gd
> +var _next_linkage: ModLoaderHook
I personally would prefer `_next_link`, `next_hook` or `_next_mod_hook_call`.
I never heard linkage before 😄

2024-11-17 19:09 UTC, KANAjetzt commented on addons/mod_loader/api/hook.gd
> +var _return_val: Variant
I think if we do `reference_object` we can also do `_return_value`

2024-11-17 19:09 UTC, KANAjetzt commented on addons/mod_loader/api/mod.gd
> +## ## Parameters can be manipulated easily by changing what is passed into .execute_next()
Nitpick: No need for doc comment above function names in the example?

2024-11-17 19:09 UTC, KANAjetzt commented on addons/mod_loader/internal/hooks.gd
> +	# Create a hook chain which will recursively call down until the vanilla method is reached
I would love a small example and a more detailed description on how the chain works here.

2024-11-17 23:18 UTC, Qubus0 commented on addons/mod_loader/api/hook.gd
> +var _return_val: Variant
ima delete it instead 😤
finally worked out how to not need it, not sure why there was a knot in my brain that didn't let me before

2024-11-17 23:19 UTC, Qubus0 commented on addons/mod_loader/internal/hooks.gd
> +	# Create a hook chain which will recursively call down until the vanilla method is reached
added better explanations in `hook.gd`

2024-11-18 20:35 UTC, pirey0 requested changes

2024-11-18 20:35 UTC, pirey0 commented on addons/mod_loader/internal/hooks.gd
> +	ModLoaderLog.debug('Added hook "%s" to to method: "%s" in script: "%s"'
duplicate "to" `to to`

2024-11-18 20:35 UTC, pirey0 commented on addons/mod_loader/internal/hooks.gd
> +	hooks.reverse()
If my understanding of reverse is correct this will flip-flop the order of mod-calls every time a function is called

2024-11-18 20:35 UTC, pirey0 commented on addons/mod_loader/internal/hooks.gd
> +	var chain_hook := ModLoaderHook.new(vanilla_method)
I would try to get all calls in 1 ModLoaderHook instead of 1 per callback

2024-11-18 21:22 UTC, Qubus0 commented on addons/mod_loader/internal/hooks.gd
> +	hooks.reverse()
this was only done once when creating the chain. otherwise yes that would have been the case. not used anymore anyway tho

2024-11-19 21:49 UTC, Alexejhero commented
Are there any plans to support hooking into coroutine methods and/or having our own hooks be coroutines by awaiting execute_next?

2024-11-20 14:32 UTC, Qubus0 commented
good point, i have a feeling we might currently be breaking every method that is called with await.. issue being that these methods aren't marked as async in any way so they are hard to detect with the preprocessor.
at least we can prevent breaking a whole file when we implement 
- #426

2024-11-22 11:59 UTC, KANAjetzt reviewed
Tested the provided example project in-editor and exported. Looks good 👍

2024-11-22 11:59 UTC, KANAjetzt commented on addons/mod_loader/api/hook_chain.gd
> +	if not _callback_index >= 0:
```suggestion
	if _callback_index < 0:
```

2024-11-22 11:59 UTC, KANAjetzt commented on addons/mod_loader/api/hook_chain.gd
> +	var callback =  _callbacks[_callback_index]
```suggestion
	var callback := _callbacks[_callback_index]
```

Is there a reason why we not want to use a specific type for the callbacks?

2024-11-22 11:59 UTC, KANAjetzt commented on addons/mod_loader/api/hook_chain.gd
> +var _callbacks := []
```suggestion
var _callbacks: Array[Callable] = []
```

2024-11-22 11:59 UTC, KANAjetzt commented on addons/mod_loader/api/hook_chain.gd
> +func _init(reference_object: Object, callbacks: Array) -> void:
```suggestion
func _init(reference_object: Object, callbacks: Array[Callable]) -> void:
```

2024-11-22 13:58 UTC, Qubus0 commented on addons/mod_loader/api/hook_chain.gd
> +func _init(reference_object: Object, callbacks: Array) -> void:
i prefer leaving this one untyped since that is less hassle when creating a new chain (allows using `[vanilla_method] + hooks` directly without casting variables with assign again.. like done in #458)

2024-11-22 22:14 UTC, KANAjetzt commented on addons/mod_loader/api/hook_chain.gd
> +func _init(reference_object: Object, callbacks: Array) -> void:
That's worth a code comment so we can remember why it's untyped.

2024-11-23 10:17 UTC, merged