fix: Errors from log.gd when using the export plugin
GodotModding/godot-mod-loader pull request #456
Opened 2024-11-20 14:47 UTC by Alexejhero

![image](https://github.com/user-attachments/assets/25740139-f4d0-4448-91df-39338b8184bf)

ModLoaderStore exists, however none of its fields are available when being used from the tool, so `if ModLoaderStore` would return true and cause a bunch of errors

Godot version: 4.2.2

2024-11-20 15:59 UTC, Qubus0 commented
tracked in #456 
thanks for the report though

2024-11-20 16:00 UTC, Qubus0 commented
ah wait that's a pr not an issue 😅

2024-11-20 16:12 UTC, KANAjetzt requested changes
Thanks for the PR!  

As suggested in the title of issue #437, we can use `.process_script()` instead of `.process_script_verbose()` in the Export Plugin to prevent these errors.

https://github.com/GodotModding/godot-mod-loader/blob/766ee3e22ea39b30e1dd5d5d2c1aca0d97df0170/addons/mod_loader/_export_plugin/export_plugin.gd#L25

2024-11-20 18:05 UTC, Alexejhero commented
> Thanks for the PR!
> 
> As suggested in the title of issue #437, we can use `.process_script()` instead of `.process_script_verbose()` in the Export Plugin to prevent these errors.
> 
> https://github.com/GodotModding/godot-mod-loader/blob/766ee3e22ea39b30e1dd5d5d2c1aca0d97df0170/addons/mod_loader/_export_plugin/export_plugin.gd#L25

While that might be true, that doesn't change the fact that the current log script improperly checks for the existence of `ModLoaderStore`. This PR fixes that issue by properly checking for its existence. This change is not mutually exclusive to the one suggested in #437

2024-11-21 09:08 UTC, KANAjetzt commented
Fair point. I need to check again why these checks are needed in the first place.
What do you think @Qubus0

2024-11-21 13:17 UTC, Qubus0 commented
At this point we could even think about just adding @tool to ModLoaderLog.. there are a few instances where logs would be nice in the editor and in those cases we've already added is_silent.. if using static variables to store stuff in ModLoaderLog instead of Store works out, I think just adding tool would be the way to go. In general, not only for this issue. 

For now I'd still go without _verbose to avoid smacking the same issue with two different solutions

2024-11-21 16:59 UTC, KANAjetzt commented
Looks like the check got added during 3 to 4 conversion.
https://github.com/GodotModding/godot-mod-loader/pull/342/files

2024-12-24 11:33 UTC, KANAjetzt commented
@Alexejhero I checked again, and the additional check is only necessary if code referencing `ModLoaderStore` is executed in the editor. The export plugin should be the only component interacting with it in this way. Adding the suggested lookups for all logs seems excessive when we can simply avoid logging anything by using `.process_script()` instead of `.process_script_verbose()`.

2024-12-25 08:14 UTC, Alexejhero commented
> @Alexejhero I checked again, and the additional check is only necessary if code referencing `ModLoaderStore` is executed in the editor. The export plugin should be the only component interacting with it in this way. Adding the suggested lookups for all logs seems excessive when we can simply avoid logging anything by using `.process_script()` instead of `.process_script_verbose()`.

I only added that to 3 places, there are 3 other places that already had a check. That check that got added during 3 to 4 conversion _doesn't work_ so it should be fixed regardless of whether or not adding this to 3 extra places seems excessive.

I only added the additional check to functions that could feasibly be called in the editor, and could result in an error.

What makes you think they are excessive? Are you talking about nano-optimizations?

2025-01-19 17:56 UTC, Alexejhero commented
Superseded by #500

2025-01-19 17:56 UTC, closed without merging